//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.DirectActivityCost = new HashSet<DirectActivityCost>();
            this.DirectProductCost = new HashSet<DirectProductCost>();
        }
    
        public int AccountID { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> AccountCost { get; set; }
    
        public virtual ICollection<DirectActivityCost> DirectActivityCost { get; set; }
        public virtual ICollection<DirectProductCost> DirectProductCost { get; set; }
    }
}
