//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.ActivityPlacement = new HashSet<ActivityPlacement>();
            this.DirectActivityCost = new HashSet<DirectActivityCost>();
        }
    
        public string ActivityID { get; set; }
        public string ActivityName { get; set; }
        public string DepartmentID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<ActivityPlacement> ActivityPlacement { get; set; }
        public virtual ICollection<DirectActivityCost> DirectActivityCost { get; set; }
    }
}
