//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic_Layer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseConnection : DbContext
    {
        public DatabaseConnection()
            : base("name=DatabaseConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Account { get; set; }
        public DbSet<Activity> Activity { get; set; }
        public DbSet<ActivityPlacement> ActivityPlacement { get; set; }
        public DbSet<CostProduct> CostProduct { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<Department> Department { get; set; }
        public DbSet<DirectActivityCost> DirectActivityCost { get; set; }
        public DbSet<DirectProductCost> DirectProductCost { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<EmployeePlacement> EmployeePlacement { get; set; }
        public DbSet<ExpenseBudget> ExpenseBudget { get; set; }
        public DbSet<FinancialIncome> FinancialIncome { get; set; }
        public DbSet<FinancialIncomeYear> FinancialIncomeYear { get; set; }
        public DbSet<ForecastMonitor> ForecastMonitor { get; set; }
        public DbSet<ForecastMonth> ForecastMonth { get; set; }
        public DbSet<IncomeProductCustomer> IncomeProductCustomer { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductCategory> ProductCategory { get; set; }
        public DbSet<ProductGroup> ProductGroup { get; set; }
        public DbSet<ProductPlacement> ProductPlacement { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<UserAccount> UserAccount { get; set; }
    }
}
