//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostProduct
    {
        public string CeProductID { get; set; }
        public System.DateTime CeIncomeDate { get; set; }
        public string CeProductName { get; set; }
        public int CeAmount { get; set; }
    }
}
