//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Activity = new HashSet<Activity>();
            this.EmployeePlacement = new HashSet<EmployeePlacement>();
            this.Product = new HashSet<Product>();
        }
    
        public string DepartmentID { get; set; }
        public string DepartmentName { get; set; }
    
        public virtual ICollection<Activity> Activity { get; set; }
        public virtual ICollection<EmployeePlacement> EmployeePlacement { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
