//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectActivityCost
    {
        public int ExpenseBudgetID { get; set; }
        public int ActivityCost { get; set; }
        public string ActivityID { get; set; }
        public int AccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Activity Activity { get; set; }
        public virtual ExpenseBudget ExpenseBudget { get; set; }
    }
}
