//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.ActivityPlacement = new HashSet<ActivityPlacement>();
            this.EmployeePlacement = new HashSet<EmployeePlacement>();
            this.ProductPlacement = new HashSet<ProductPlacement>();
            this.UserAccount = new HashSet<UserAccount>();
        }
    
        public long EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public int MonthSallary { get; set; }
        public int EmployeementRate { get; set; }
        public Nullable<decimal> VacancyDeduction { get; set; }
    
        public virtual ICollection<ActivityPlacement> ActivityPlacement { get; set; }
        public virtual ICollection<EmployeePlacement> EmployeePlacement { get; set; }
        public virtual ICollection<ProductPlacement> ProductPlacement { get; set; }
        public virtual ICollection<UserAccount> UserAccount { get; set; }
    }
}
