//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseBudget
    {
        public ExpenseBudget()
        {
            this.ActivityPlacement = new HashSet<ActivityPlacement>();
            this.DirectActivityCost = new HashSet<DirectActivityCost>();
            this.DirectProductCost = new HashSet<DirectProductCost>();
            this.ProductPlacement = new HashSet<ProductPlacement>();
        }
    
        public int ExpenseBudgetID { get; set; }
        public int SellLock { get; set; }
        public int ProductionLock { get; set; }
    
        public virtual ICollection<ActivityPlacement> ActivityPlacement { get; set; }
        public virtual ICollection<DirectActivityCost> DirectActivityCost { get; set; }
        public virtual ICollection<DirectProductCost> DirectProductCost { get; set; }
        public virtual ICollection<ProductPlacement> ProductPlacement { get; set; }
    }
}
