//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeProductCustomer
    {
        public string IeProductID { get; set; }
        public System.DateTime IeIncomeDate { get; set; }
        public int IeCustomerID { get; set; }
        public string IeProductName { get; set; }
        public string IeCustomerName { get; set; }
        public int IeAmount { get; set; }
    }
}
