//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public ProductCategory()
        {
            this.ProductGroup = new HashSet<ProductGroup>();
        }
    
        public string ProductCategoryID { get; set; }
        public string ProductCategoryName { get; set; }
    
        public virtual ICollection<ProductGroup> ProductGroup { get; set; }
    }
}
