//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPlacement
    {
        public long EmployeeID { get; set; }
        public string ProductID { get; set; }
        public int ExpenseBudgetID { get; set; }
        public decimal ProductAllocate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ExpenseBudget ExpenseBudget { get; set; }
        public virtual Product Product { get; set; }
    }
}
