//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.DirectProductCost = new HashSet<DirectProductCost>();
            this.FinancialIncome = new HashSet<FinancialIncome>();
            this.ProductPlacement = new HashSet<ProductPlacement>();
        }
    
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductGroupID { get; set; }
        public string DepartmentID { get; set; }
        public string ProductCategoryID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<DirectProductCost> DirectProductCost { get; set; }
        public virtual ICollection<FinancialIncome> FinancialIncome { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
        public virtual ICollection<ProductPlacement> ProductPlacement { get; set; }
    }
}
