//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public Nullable<decimal> EmployeeID { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public int PermissionLevel { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
