//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Account
{
	public virtual int AccoundID
	{
		get;
		set;
	}

	public virtual string AccountName
	{
		get;
		set;
	}

	public virtual int AccountCost
	{
		get;
		set;
	}

}

