//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FinancialIncome
{
	public virtual Product product
	{
		get;
		set;
	}

	public virtual Customer customer
	{
		get;
		set;
	}

	public virtual int Agreement
	{
		get;
		set;
	}

	public virtual bool GradeA
	{
		get;
		set;
	}

	public virtual int Addition
	{
		get;
		set;
	}

	public virtual bool GradeT
	{
		get;
		set;
	}

	public virtual int Budget
	{
		get;
		set;
	}

	public virtual int Hours
	{
		get;
		set;
	}

	public virtual string Comments
	{
		get;
		set;
	}

	public virtual long FinancialIncomeYearID
	{
		get;
		set;
	}

	public virtual void CalculateBudget()
	{
		throw new System.NotImplementedException();
	}

}

