//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class LogicController
{
	public virtual CalculateExpenseBudget CalculateExpenseBudget
	{
		get;
		set;
	}

	public virtual ManagerProduct ManagerProduct
	{
		get;
		set;
	}

	public virtual ManagerGroupCategory ManagerGroupCategory
	{
		get;
		set;
	}

	public virtual ManagerEmployee ManagerEmployee
	{
		get;
		set;
	}

	public virtual ManagerUserAccount ManagerUserAccount
	{
		get;
		set;
	}

	public virtual ManagerActivity ManagerActivity
	{
		get;
		set;
	}

	public virtual ManagerAccount ManagerAccount
	{
		get;
		set;
	}

	public virtual ManagerCustomer ManagerCustomer
	{
		get;
		set;
	}

	public virtual ManagerExpense ManagerExpense
	{
		get;
		set;
	}

	public virtual ManagerIncome ManagerIncome
	{
		get;
		set;
	}

	public virtual ManagerForecast ManagerForecast
	{
		get;
		set;
	}

	public virtual void ControlUserAuthority(ManagerUserAccount userAccount)
	{
		throw new System.NotImplementedException();
	}

}

