//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ManagerExpense
{
	public virtual ExpenseBudget ExpenseBudget
	{
		get;
		set;
	}

	public virtual void Lock()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CalculateCostProduct(Product product)
	{
		throw new System.NotImplementedException();
	}

	public virtual void CalculateCostActivity(Activity activity)
	{
		throw new System.NotImplementedException();
	}

	public virtual void CalculateExpenseBudget()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CalculateAnnualProduct(Employee employee, Product product)
	{
		throw new System.NotImplementedException();
	}

	public virtual void CalculateAnnualActivity(Employee employee, Activity activity)
	{
		throw new System.NotImplementedException();
	}

}

