//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class UserAccount
{
	public virtual string Username
	{
		get;
		set;
	}

	public virtual string Password
	{
		get;
		set;
	}

	public virtual enum PermissionLevel
	{
		get;
		set;
	}

	public virtual Employee Employee
	{
		get;
		set;
	}

}

