//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Employee
{
	public virtual long EmployeeID
	{
		get;
		set;
	}

	public virtual string EmployeeName
	{
		get;
		set;
	}

	public virtual int MonthSallery
	{
		get;
		set;
	}

	public virtual int EmploymentRate
	{
		get;
		set;
	}

	public virtual double VacancyDeduction
	{
		get;
		set;
	}

	public virtual double AnnualEmployee
	{
		get;
		set;
	}

	public virtual double Diff
	{
		get;
		set;
	}

}

