//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ForecastMonitoring
{
	public virtual Product product
	{
		get;
		set;
	}

	public virtual int OutcomeMonth
	{
		get;
		set;
	}

	public virtual int OutcomeAcc
	{
		get;
		set;
	}

	public virtual int Reprocessed
	{
		get;
		set;
	}

	public virtual int Forecast
	{
		get;
		set;
	}

	public virtual int ForecastBudget
	{
		get;
		set;
	}

	public virtual int Trend
	{
		get;
		set;
	}

	public virtual void CalculateTrend()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CalculateOutcomeMonth()
	{
		throw new System.NotImplementedException();
	}

	public virtual void LockForecast()
	{
		throw new System.NotImplementedException();
	}

}

