//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class LogIn
{
	public virtual ManagerUserAccount ManagerUserAccount
	{
		get;
		set;
	}

	public virtual void UserLogIn(string userName, string password)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AuthenticateUser(UserAccount userAccount)
	{
		throw new System.NotImplementedException();
	}

}

