//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ManagerCustomer
{
	public virtual Customer Customer
	{
		get;
		set;
	}

	public virtual ManagerIncome ManagerIncome
	{
		get;
		set;
	}

	public virtual void CreateCustomer()
	{
		throw new System.NotImplementedException();
	}

}

