//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ManagerActivity
{
	public virtual Activity Activity
	{
		get;
		set;
	}

	public virtual ManagerExpense ManagerExpense
	{
		get;
		set;
	}

	public virtual void CreateActivity()
	{
		throw new System.NotImplementedException();
	}

}

