//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ManagerIncome
{
	public virtual FinancialIncome FinancialIncome
	{
		get;
		set;
	}

	public virtual ManagerForecast ManagerForecast
	{
		get;
		set;
	}

	public virtual void LockIncome()
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddToDatabase()
	{
		throw new System.NotImplementedException();
	}

	public virtual void FinancialIncomeProduct(Product product)
	{
		throw new System.NotImplementedException();
	}

	public virtual void FinancialIncomeCustomer(Customer customer)
	{
		throw new System.NotImplementedException();
	}

}

