//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ManagerEmployee
{
	public virtual Employee Employee
	{
		get;
		set;
	}

	public virtual ManagerUserAccount ManagerUserAccount
	{
		get;
		set;
	}

	public virtual ManagerExpense ManagerExpense
	{
		get;
		set;
	}

	public virtual void CreateEmployee(Department department)
	{
		throw new System.NotImplementedException();
	}

}

