//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ManagerProduct
{
	public virtual Product Product
	{
		get;
		set;
	}

	public virtual ManagerIncome ManagerIncome
	{
		get;
		set;
	}

	public virtual ManagerExpense ManagerExpense
	{
		get;
		set;
	}

	public virtual void CreateProduct(Department department, ProductGroup productGroup, ProductCategory productCategory)
	{
		throw new System.NotImplementedException();
	}

}

