//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ManagerUserAccount
{
	public virtual UserAccount UserAccount
	{
		get;
		set;
	}

	public virtual LogicController LogicController
	{
		get;
		set;
	}

	public virtual void CreateUserAccount(Employee employee)
	{
		throw new System.NotImplementedException();
	}

}

